### ISSUE TITLE
Вопрос про выбор архитектурного подхода

### ISSUE THREAD

**Issue by Turbozanik** [awaik/swipe_bloc_flutter#1]
Добрый день! Я хотел узнать на какой архитектуре Вы остановили свой выбор, читал Вашу статью про самописную реализацию bloc, сделали свою архитектуру на ее основе, потом попробовали bloc, getx, riverpod, а опыта больших проектов чтобы сравнить их в реальных условиях нету.
И как-то так получается ,что везде свои + и -, хотел бы узнать Ваше мнение, с чем Вы сейчас работаете, возможно у Вас какой-то свой подход.

**Comment by awaik** [comment]
Здравствуйте,
на рабочих проектах (прямо сейчас работаю в большом проекте соцсети) пришел к тому, что использую:
1. чистую архитектуру для разделения кода на слои (бэкенд, авторизация, модели, обработки, передачи данных между приложениями, бэком и т.п.)
2. для работы с состояниями и потоками в UI использую Getx 
https://pub.dev/packages/get

BLoC требует слишком много кода и слишком усложняет простые действия (сугубо личное мнение)

**Comment by Turbozanik** [comment]
Круто, в общем к блоку у меня теже претензии, слегка громоздко и не прозрачно.
А в getx все компоненты используете?

**Comment by awaik** [comment]
да, все, включая навигацию
с ним удобно анимацию делать, вызовы окон и т.п.

**Comment by Turbozanik** [comment]
Окей, большое спасибо, пойду ещё раз читать, меня прям сильно смутила реализация di.
